[window]
## Default terminal width
dimensions.columns = 140
## Default terminal height
dimensions.lines = 40

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
